setwd("~/Documents/Self-learning/DS/Data Science-JHU/4-Plot data/project 2")
unzip("exdata%2Fdata%2FNEI_data.zip")
NEI <- readRDS("summarySCC_PM25.rds")
SCC <- readRDS("Source_Classification_Code.rds")
NEI7=subset(NEI,fips=="24510" & type=="ON-ROAD")
NEI8<-tapply(NEI7$Emissions,NEI7$year,sum)
NEI8=as.data.frame(as.table(NEI8))
colnames(NEI8)<-c("Year","Total_Emission")
NEI9=subset(NEI,fips=="06037" & type=="ON-ROAD")
NEI10<-tapply(NEI9$Emissions,NEI9$year,sum)
NEI10=as.data.frame(as.table(NEI10))
colnames(NEI10)<-c("Year","Total_Emission")
NEI11=rbind(NEI8,NEI10)
NEI11$City<-c("BA","BA","BA","BA","LA","LA","LA","LA")
library(ggplot2)
g=ggplot(NEI11,aes(Year,Total_Emission,group=1,color=City))
g1=g+geom_point(aes(shape=City,color=City),size=3)+geom_line(aes(color=City,group=City))
g2=g1+xlab("Year")+ylab("Total PM2.5 Emissions (Tons)")+ggtitle("Total PM2.5 Emissions in BA and LA")
print(g2)
dev.copy(png,"plot6.png",width=480, height=480)
dev.off()
#LA  