setwd("~/Documents/Self-learning/DS/Data Science-JHU/4-Plot data/project 2")
unzip("exdata%2Fdata%2FNEI_data.zip")
NEI <- readRDS("summarySCC_PM25.rds")
SCC <- readRDS("Source_Classification_Code.rds")
NEI7=subset(NEI,fips=="24510" & type=="ON-ROAD")
NEI8<-tapply(NEI7$Emissions,NEI7$year,sum)
NEI8=as.data.frame(as.table(NEI8))
colnames(NEI8)<-c("Year","Total_Emission")
library(ggplot2)
g=ggplot(NEI8,aes(Year,Total_Emission))
g1=g+ylab("Total PM2.5 Emissions (Tons)")+geom_bar(stat="identity")
g2=g1+ggtitle("Total PM2.5 Emissions from vehicles in Baltimore")
print(g2)
dev.copy(png,"plot5.png",width=480, height=480)
dev.off()

