setwd("~/Documents/Self-learning/DS/Data Science-JHU/4-Plot data/project 2")
unzip("exdata%2Fdata%2FNEI_data.zip")
NEI <- readRDS("summarySCC_PM25.rds")
SCC <- readRDS("Source_Classification_Code.rds")
NEI2=subset(NEI,fips=="24510")
NEI3<-tapply(NEI2$Emissions,NEI2$year,sum)
barplot(NEI3,xlab = "Year",ylab="Total PM2.5 Emissions (Tons)", main="Total PM2.5 Emissions in Baltimore", ylim=c(0,4000))
dev.copy(png,"plot2.png",width=480, height=480)
dev.off()
#I don't think so.
