setwd("~/Documents/Self-learning/DS/Data Science-JHU/4-Plot data")
data1=unzip("data1.zip")
data11<-read.table(data1,sep=";",header = T)
data111<-subset(data11,Date=="1/2/2007"|Date=="2/2/2007")
Global_active_power<-as.numeric(as.character(data111$Global_active_power))
hist(Global_active_power,main="Global Active Power",col="red",xlab="Global Active Power (kilowatts)")
dev.copy(png,"plot1.png",width=480, height=480)
dev.off()